language: node_js

node_js: "node"

os:
  - linux
  - osx
  - windows

#before_install: |
#  if [ "${TRAVIS_OS_NAME}" = 'windows' ]; then
#    cp test-projects/msdmo.dll /c/Windows/System32/
#    npm config set script-shell 'bash'
#  fi

script: |
  if [ "${TRAVIS_OS_NAME}" = 'linux' ]; then
    xvfb-run npm start
  else
    npm start
  fi
